name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NAME: "Rust Test"
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Lint
        run: |
          cargo fmt -- --check
          npx prettier --check ./.github/**/* ./

  build-nd-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
