name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NAME: "Rust Test"
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-nd-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1

      - name: Setup | Rust | Nightly
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy rustfmt

      - uses: davidB/rust-cargo-make@v1
        name: Install Cargo Make

      - uses: actions/cache@v3
        name: Cache Cargo Files
        with:
          path: |
            target/release
            target/debug
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Lint
        run: |
          cargo fmt -- --check
          npx prettier --check ./.github/**/* ./
